import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";
import NextThemeProvider from "../Provider/NextThemeProvider";


const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// ${geistSans.variable} ${geistMono.variable}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      themes="light"
      className={`${robotoSans.className} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <NextThemeProvider>
          <Navbar></Navbar>
          <main>
            {children}
          </main>
          <Footer></Footer>
          <Toaster />
        </NextThemeProvider>
      </body>
    </html>
  );
}
